sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mysql123456
  localfile:
      upload-dir: /Users/xinzhang/Desktop/sky-take-out/uploads
      base-url: http://localhost:8080/uploads
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx28b3c3489c7dc616
    secret: 60ee0a77148d0e8662c8aa4d78f8a0f0